import openai

# Set your OpenAI API key
openai.api_key = ""  # Make sure to replace with your actual API key

def get_chatbot_response(user_input):
    """
    Function to get a response from GPT-3.5 or GPT-4 chatbot.
    :param user_input: The message input by the user.
    :return: The response generated by GPT-3.5 or GPT-4.
    """
    try:
        # Send the user's input to the GPT model using the chat-based API
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",  # Use gpt-3.5-turbo if you don't have access to gpt-4
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": user_input}
            ],
            max_tokens=150,
            temperature=0.7
        )

        # Extract and return the chatbot's response from the API response
        return response['choices'][0]['message']['content'].strip()

    except Exception as e:
        return f"Error: {e}"

def start_chat():
    """
    Function to start the chatbot conversation.
    """
    print("Chatbot: Hello! I am your AI assistant. How can I help you today?")
    
    while True:
        user_input = input("You: ")
        
        # Exit the chat loop if the user types 'exit', 'quit', or 'bye'
        if user_input.lower() in ['exit', 'quit', 'bye']:
            print("Chatbot: Goodbye! Have a great day.")
            break
        
        # Get the chatbot response and print it
        chatbot_response = get_chatbot_response(user_input)
        print(f"Chatbot: {chatbot_response}")

if __name__ == "__main__":
    start_chat()
